language: cpp

before_install:
- sudo apt-get update -qq

compiler: gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

script: cmake ./ && cmake --build ./ --target enact -- -j 2
